version: "3"
services:
  app_python:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "../app_python/data/visits:/var/app-python/visits"