apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-python
  name: app-python
  namespace: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - image: khaledismaeel/app_python
        name: app-python
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: token
                key: token
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
      restartPolicy: Always
