apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-python
  name: app-python
  namespace: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - image: khaledismaeel/app_python
        name: app-python
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
      restartPolicy: Always
