apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-python
  name: app-python
  namespace: app-python
spec:
  ports:
  - nodePort: 30000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: app-python
  type: LoadBalancer
